import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(
    page_title="Enterprise Customer Intelligence Engine", 
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="collapsed"
)


st.markdown("""
    <style>
    .metric-card {
        background-color: #1e222b;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #4A90E2;
        margin-bottom: 10px;
    }
    .sub-card {
        background-color: #14171c;
        padding: 15px;
        border-radius: 8px;
        border: 1px solid #2d3139;
        text-align: center;
    }
    </style>
""", unsafe_allow_html=True)

st.title("🎯 Enterprise Customer Intelligence Engine")
st.markdown("##### *Prescriptive Data Pipeline & K-Means Optimization for Marketing Velocity*")
st.markdown("---")

@st.cache_data
def load_data():
    import os
    
    cloud_path = "rfm_segments.csv"
    local_path = "03-prescriptive_analytics/rfm_customer_segmentation/dashboard/rfm_segments.csv"
    
    if os.path.exists(cloud_path):
        return pd.read_csv(cloud_path)
    return pd.read_csv(local_path)

try:
    df = load_data()

    # 2. Global Executive Metrics
    total_customers = df['customer_id'].nunique()
    total_revenue = df['monetary'].sum()
    avg_spend = df['monetary'].mean()

    m_col1, m_col2, m_col3 = st.columns(3)
    with m_col1:
        st.markdown(f"<div class='metric-card'><h5>👥 Total Segmented Customers</h5><h2>{total_customers:,}</h2></div>", unsafe_allow_html=True)
    with m_col2:
        st.markdown(f"<div class='metric-card' style='border-left-color: #2ECC71;'><h5>💰 Captured Revenue Pool</h5><h2>${total_revenue:,.2f}</h2></div>", unsafe_allow_html=True)
    with m_col3:
        st.markdown(f"<div class='metric-card' style='border-left-color: #9B59B6;'><h5>💳 Avg Customer Lifetime Value</h5><h2>${avg_spend:,.2f}</h2></div>", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # 3. Clean Two-Tab Navigation
    tab1, tab2 = st.tabs([
        "📊 Cluster Visualizations & Strategy Matrix", 
        "⚙️ Interactive Data Explorer (Filtering Engine)"
    ])

    with tab1:
        col_chart1, col_chart2 = st.columns([3, 2])
        
        with col_chart1:
            st.subheader("Customer Distribution Space")
            fig_scatter = px.scatter(
                df, x="frequency", y="monetary", color="segment_name",
                hover_data=["customer_id", "category_diversity"],
                labels={"frequency": "Items Purchased (Frequency)", "monetary": "Total Spend ($)"},
                color_discrete_sequence=px.colors.qualitative.Bold,
                log_y=True
            )
            fig_scatter.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(fig_scatter, use_container_width=True)

        with col_chart2:
            st.subheader("Market Share by Headcount")
            segment_counts = df['segment_name'].value_counts().reset_index()
            fig_pie = px.pie(
                segment_counts, names="segment_name", values="count",
                color_discrete_sequence=px.colors.qualitative.Bold,
                hole=0.4
            )
            fig_pie.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(fig_pie, use_container_width=True)

        st.markdown("---")
    
        st.subheader("🔍 Interactive Segment Contribution Analyzer")
        selected_prof = st.radio(
            "Select Target Segment Profile for KPI Breakdown:",
            options=['Whales / VIPs', 'High-Value Loyals', 'Regulars', 'Casual Shoppers'],
            horizontal=True
        )
        
        prof_df = df[df['segment_name'] == selected_prof]
        prof_revenue = prof_df['monetary'].sum()
        revenue_share = (prof_revenue / total_revenue) * 100
        avg_diversity = prof_df['category_diversity'].mean()
        
        kpi_col1, kpi_col2, kpi_col3 = st.columns(3)
        with kpi_col1:
            st.markdown(f"<div class='sub-card'><h6>Revenue Generated by Segment</h6><h3 style='color: #2ECC71;'>${prof_revenue:,.2f}</h3></div>", unsafe_allow_html=True)
        with kpi_col2:
            st.markdown(f"<div class='sub-card'><h6>Total Financial Value Share</h6><h3 style='color: #F1C40F;'>{revenue_share:.1f}% of Revenue</h3></div>", unsafe_allow_html=True)
        with kpi_col3:
            st.markdown(f"<div class='sub-card'><h6>Avg. Product Categories Explored</h6><h3 style='color: #4A90E2;'>{avg_diversity:.1f} Categories</h3></div>", unsafe_allow_html=True)

        st.markdown("---")

        st.subheader("📋 Executive Tactical Action Matrix")
        st.markdown("##### *Segments structured in descending order of Total Capital Value Tier*")
        
        matrix_data = []
        for seg in ['Whales / VIPs', 'High-Value Loyals', 'Regulars', 'Casual Shoppers']:
            seg_df = df[df['segment_name'] == seg]
            
            if seg == 'Whales / VIPs':
                strat = "👑 VIP Circle: Dedicated relations managers, zero-cost priority shipping, early brand-drop windows."
            elif seg == 'High-Value Loyals':
                strat = "🔒 Value Lock: Introduce subscription tiers (free-shipping bundles) & point multipliers."
            elif seg == 'Regulars':
                strat = "🎯 Cross-Sell: Feed 'Complete the Look' recommendation matrices into account UI."
            else:
                strat = "⏳ Reactivation: Short-horizon flash sale vouchers (48-hour expirations) to clear low-margin inventory."
                
            matrix_data.append({
                "Segment Rank": "⭐ Tier 1" if seg == 'Whales / VIPs' else "🔹 Tier 2" if seg == 'High-Value Loyals' else "🔸 Tier 3" if seg == 'Regulars' else "💤 Tier 4",
                "Customer Profile": seg,
                "Headcount": f"{len(seg_df):,}",
                "Avg. Items Bought": f"{int(seg_df['frequency'].mean())} units",
                "Avg. Lifetime Spend": f"${seg_df['monetary'].mean():,.2f}",
                "Prescriptive Marketing Execution": strat
            })
            
        summary_matrix = pd.DataFrame(matrix_data)
        st.dataframe(summary_matrix, use_container_width=True, hide_index=True)
        st.markdown("<br>", unsafe_allow_html=True)
        st.info("💡 **Developer Note:** This matrix serves as the direct pipeline feed for automated email trigger logic in the CRM backend.")

    with tab2:
        st.subheader("⚙️ Customer Lead Generation & Granular Filtering Engine")
        st.markdown("Customize your query criteria to filter and download targeted lists of customer profiles instantly.")
        
        c1, c2, c3 = st.columns(3)
        
        with c1:
            segment_filter = st.multiselect(
                "Filter by Customer Profile:",
                options=df['segment_name'].unique(),
                default=df['segment_name'].unique()
            )
        with c2:
            min_spend, max_spend = int(df['monetary'].min()), int(df['monetary'].max())
            spend_range = st.slider(
                "Total Lifetime Spend Range ($):",
                min_value=min_spend, max_value=max_spend,
                value=(min_spend, max_spend)
            )
        with c3:
            min_freq, max_freq = int(df['frequency'].min()), int(df['frequency'].max())
            freq_range = st.slider(
                "Items Purchased Count (Frequency):",
                min_value=min_freq, max_value=max_freq,
                value=(min_freq, max_freq)
            )
            
        filtered_df = df[
            (df['segment_name'].isin(segment_filter)) &
            (df['monetary'].between(spend_range[0], spend_range[1])) &
            (df['frequency'].between(freq_range[0], freq_range[1]))
        ]
        
        st.success(f"🔍 Found **{len(filtered_df):,}** profiles matching your active parameters.")
        st.dataframe(filtered_df, use_container_width=True, hide_index=True)
        
        csv_download = filtered_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Export Target Segment Customer List (CSV)",
            data=csv_download,
            file_name="targeted_customer_leads.csv",
            mime="text/csv"
        )

except FileNotFoundError:
    st.error("Resource file 'rfm_segments.csv' missing. Run your data backend execution scripts first.")