import os
import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(
    page_title="Enterprise Customer Intelligence Engine", 
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
    <style>
    .metric-card {
        background-color: #1e222b;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #4A90E2;
        margin-bottom: 10px;
    }
    .sub-card {
        background-color: #14171c;
        padding: 15px;
        border-radius: 8px;
        border: 1px solid #2d3139;
        text-align: center;
    }
    </style>
""", unsafe_allow_html=True)

st.title("🎯 Enterprise Customer Intelligence Engine")
st.markdown("##### *Prescriptive Data Pipeline & K-Means Optimization for Marketing Velocity*")
st.markdown("---")

# 2. Robust Multi-Path Data Ingestion
@st.cache_data
def load_data():
    possible_paths = [
        os.path.join(os.path.dirname(__file__), '..', 'data', 'rfm_segments.csv'),
        os.path.join(os.path.dirname(__file__), 'rfm_segments.csv'),
        'data/rfm_segments.csv',
        'prescriptive_analytics/rfm_customer_segmentation/data/rfm_segments.csv',
        'rfm_segments.csv'
    ]
    
    for path in possible_paths:
        if os.path.exists(path):
            return pd.read_csv(path)
            
    st.error("Resource file 'rfm_segments.csv' missing. Please run your SQL pipeline script first.")
    st.stop()

df = load_data()

# 3. Column Standardization & Mapping
column_mapping = {
    'total_monetary_spend': 'monetary',
    'total_orders': 'frequency',
    'unique_products_bought': 'category_diversity',
    'customer_lifecycle_segment': 'segment_name'
}
df = df.rename(columns=column_mapping)

if 'category_diversity' not in df.columns:
    df['category_diversity'] = 1

if 'segment_name' not in df.columns:
    df['segment_name'] = 'General Customer'

# 4. Global Executive Metrics
total_customers = df['customer_id'].nunique()
total_revenue = df['monetary'].sum()
avg_spend = df['monetary'].mean()

m_col1, m_col2, m_col3 = st.columns(3)
with m_col1:
    st.markdown(f"<div class='metric-card'><h5>👥 Total Segmented Customers</h5><h2>{total_customers:,}</h2></div>", unsafe_allow_html=True)
with m_col2:
    st.markdown(f"<div class='metric-card' style='border-left-color: #2ECC71;'><h5>💰 Captured Revenue Pool</h5><h2>${total_revenue:,.2f}</h2></div>", unsafe_allow_html=True)
with m_col3:
    st.markdown(f"<div class='metric-card' style='border-left-color: #9B59B6;'><h5>💳 Avg Customer Lifetime Value</h5><h2>${avg_spend:,.2f}</h2></div>", unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# 5. Clean Two-Tab Navigation
tab1, tab2 = st.tabs([
    "📊 Cluster Visualizations & Strategy Matrix", 
    "⚙️ Interactive Data Explorer (Filtering Engine)"
])

with tab1:
    col_chart1, col_chart2 = st.columns([3, 2])
    
    with col_chart1:
        st.subheader("Customer Distribution Space")
        fig_scatter = px.scatter(
            df, x="frequency", y="monetary", color="segment_name",
            hover_data=["customer_id", "category_diversity"],
            labels={"frequency": "Items Purchased (Frequency)", "monetary": "Total Spend ($)"},
            color_discrete_sequence=px.colors.qualitative.Bold,
            log_y=True
        )
        fig_scatter.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig_scatter, use_container_width=True)

    with col_chart2:
        st.subheader("Market Share by Headcount")
        segment_counts = df['segment_name'].value_counts().reset_index()
        segment_counts.columns = ['segment_name', 'count']
        fig_pie = px.pie(
            segment_counts, names="segment_name", values="count",
            color_discrete_sequence=px.colors.qualitative.Bold,
            hole=0.4
        )
        fig_pie.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig_pie, use_container_width=True)

    st.markdown("---")

    st.subheader("🔍 Interactive Segment Contribution Analyzer")
    available_segments = sorted(df['segment_name'].unique().tolist())
    selected_prof = st.radio(
        "Select Target Segment Profile for KPI Breakdown:",
        options=available_segments,
        horizontal=True
    )
    
    prof_df = df[df['segment_name'] == selected_prof]
    prof_revenue = prof_df['monetary'].sum()
    revenue_share = (prof_revenue / total_revenue) * 100 if total_revenue > 0 else 0
    avg_diversity = prof_df['category_diversity'].mean()
    
    kpi_col1, kpi_col2, kpi_col3 = st.columns(3)
    with kpi_col1:
        st.markdown(f"<div class='sub-card'><h6>Revenue Generated by Segment</h6><h3 style='color: #2ECC71;'>${prof_revenue:,.2f}</h3></div>", unsafe_allow_html=True)
    with kpi_col2:
        st.markdown(f"<div class='sub-card'><h6>Total Financial Value Share</h6><h3 style='color: #F1C40F;'>{revenue_share:.1f}% of Revenue</h3></div>", unsafe_allow_html=True)
    with kpi_col3:
        st.markdown(f"<div class='sub-card'><h6>Avg. Product Categories Explored</h6><h3 style='color: #4A90E2;'>{avg_diversity:.1f} Categories</h3></div>", unsafe_allow_html=True)

    st.markdown("---")

    st.subheader("📋 Executive Tactical Action Matrix")
    st.markdown("##### *Segments structured in descending order of Total Capital Value Tier*")
    
    strategy_mapping = {
        'Tier 1: High-Volume VIP': "👑 VIP Circle: Dedicated relations managers, zero-cost priority shipping, early brand-drop windows.",
        'Tier 2: High-Value Whales': "🔒 Value Lock: Introduce subscription tiers (free-shipping bundles) & point multipliers.",
        'Tier 3: Core Regulars': "🎯 Cross-Sell: Feed 'Complete the Look' recommendation matrices into account UI.",
        'Tier 4: Occasional Buyers': "⏳ Reactivation: Short-horizon flash sale vouchers (48-hour expirations) to clear low-margin inventory.",
        'Tier 5: Low-Spend / Churn-Risk': "💡 Win-Back: Automated threshold discounts and price-drop alerts.",
        'Whales / VIPs': "👑 VIP Circle: Dedicated relations managers, zero-cost priority shipping, early brand-drop windows.",
        'High-Value Loyals': "🔒 Value Lock: Introduce subscription tiers & point multipliers.",
        'Regulars': "🎯 Cross-Sell: Feed recommendations into account UI.",
        'Casual Shoppers': "⏳ Reactivation: Short-horizon flash sale vouchers."
    }
    
    matrix_data = []
    for seg in available_segments:
        seg_df = df[df['segment_name'] == seg]
        strat = strategy_mapping.get(seg, "Strategic targeted marketing based on behavioral cohort analysis.")
        
        matrix_data.append({
            "Customer Profile": seg,
            "Headcount": f"{len(seg_df):,}",
            "Avg. Items Bought": f"{int(seg_df['frequency'].mean())} units",
            "Avg. Lifetime Spend": f"${seg_df['monetary'].mean():,.2f}",
            "Prescriptive Marketing Execution": strat
        })
        
    summary_matrix = pd.DataFrame(matrix_data)
    st.dataframe(summary_matrix, use_container_width=True, hide_index=True)
    st.markdown("<br>", unsafe_allow_html=True)
    st.info("💡 **Developer Note:** This matrix serves as the direct pipeline feed for automated CRM targeting.")

with tab2:
    st.subheader("⚙️ Customer Lead Generation & Granular Filtering Engine")
    st.markdown("Customize query criteria to filter and download targeted customer lists instantly.")
    
    c1, c2, c3 = st.columns(3)
    
    with c1:
        segment_filter = st.multiselect(
            "Filter by Customer Profile:",
            options=available_segments,
            default=available_segments
        )
    with c2:
        min_spend, max_spend = int(df['monetary'].min()), int(df['monetary'].max())
        spend_range = st.slider(
            "Total Lifetime Spend Range ($):",
            min_value=min_spend, max_value=max_spend,
            value=(min_spend, max_spend)
        )
    with c3:
        min_freq, max_freq = int(df['frequency'].min()), int(df['frequency'].max())
        freq_range = st.slider(
            "Items Purchased Count (Frequency):",
            min_value=min_freq, max_value=max_freq,
            value=(min_freq, max_freq)
        )
        
    filtered_df = df[
        (df['segment_name'].isin(segment_filter)) &
        (df['monetary'].between(spend_range[0], spend_range[1])) &
        (df['frequency'].between(freq_range[0], freq_range[1]))
    ]
    
    st.success(f"🔍 Found **{len(filtered_df):,}** profiles matching active parameters.")
    st.dataframe(filtered_df, use_container_width=True, hide_index=True)
    
    csv_download = filtered_df.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="📥 Export Target Segment Customer List (CSV)",
        data=csv_download,
        file_name="targeted_customer_leads.csv",
        mime="text/csv"
    )